---
version: '3'

services:
              
  html-to-markdown-app:
    image: entechlog/html-to-markdown-app
    container_name: html-to-markdown-app
    build: ./docker/app/
    env_file:
      - ./.env
    command: 
      - bash 
      - -c 
      - |
        echo "Launching html-to-markdown-app"
        #
        python /usr/src/lambda_function.py --file_name ${file_name} --converter ${converter}
        #
        sleep infinity
    restart: unless-stopped
    volumes:
      - ./data:/data
      