---
version: '3'

services:
              
  ddl-to-dbt-yaml:
    image: entechlog/ddl-to-dbt-yaml
    container_name: ddl-to-dbt-yaml
    build: ./docker/app/
    env_file:
      - ./.env
    command: 
      - bash 
      - -c 
      - |
        echo "Launching ddl-to-dbt-yaml"
        #
        python /usr/src/lambda_function.py --file_name ${file_name} --formatter ${formatter}
        #
        sleep infinity
    restart: unless-stopped
    volumes:
      - ./data:/data
      