---
version: '3'

services:
              
  py-translate-app:
    image: entechlog/py-translate-app
    container_name: py-translate-app
    build: ./docker/app/
    env_file:
      - ./.env
    command: 
      - bash 
      - -c 
      - |
        echo "Launching py-translate-app"
        #
        python /usr/src/lambda_function.py --file_name ${file_name} --src_lang_cd ${src_lang_cd} --tgt_lang_cd ${tgt_lang_cd}
        #
        sleep infinity
    restart: unless-stopped
    volumes:
      - ./data:/data
      